language: erlang
dist: xenial
sudo: false
notifications:
     email:
         - backend@gameanalytics.com
otp_release:
    - 19.3
    - 20.0
    - 21.1
addons:
  apt:
    packages:
      - default-jre
install: make deps
script: make xref test dialyzer
