language: erlang
sudo: false
notifications:
     email:
         - backend@gameanalytics.com
otp_release:
    - 19.1
    - 19.3
    - R16B03
addons:
  apt:
    packages:
      - default-jre
script: "./rebar compile && ./rebar eunit skip_deps=true"
