language: erlang
dist: bionic
sudo: false
notifications:
     email:
         - backend@gameanalytics.com
otp_release:
    - 21.1
    - 22.3
    - 23.0
addons:
  apt:
    packages:
      - default-jre
install: make deps
script: make xref test dialyzer
