language: erlang
sudo: false
notifications:
     email:
         - backend@gameanalytics.com
otp_release:
    - 19.3
    - 20.0
addons:
  apt:
    packages:
      - default-jre
env:
    - GOAL=test
    # - GOAL=dialyzer % TODO
    - GOAL=xref
install: make deps
script: make ${GOAL}
