language: erlang
sudo: false
branches:
  only:
      - master
      - /^game-\d+$/
notifications:
     email:
         - backend@gameanalytics.com
otp_release:
    - 19.3
    - 20.0
addons:
  apt:
    packages:
      - default-jre
script: "./rebar compile && ./rebar eunit skip_deps=true"
